name: Build and deploy Angular app to Azure Web App - am-web-ui

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build -- --configuration AMWebUI
        working-directory: AMWebUI

      - name: Copy web.config to build output browser folder
        run: cp AMWebUI/src/web.config AMWebUI/dist/amweb-ui/browser/web.config

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: angular-build
          path: AMWebUI/dist/amweb-ui/browser

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: angular-build
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'am-web-ui'
          slot-name: 'Production'
          package: .
